### ISSUE TITLE
genhtml confused with relative file paths

### ISSUE THREAD

**Issue by ettersi** [tpapp/LocalCoverage.jl#1]
I get the following error
```
julia> generate_coverage("DummyPackage")
INFO: Testing DummyPackage
INFO: DummyPackage tests passed
Coverage.process_folder: Searching src for .jl files...
Coverage.process_file: Detecting coverage for src/DummyPackage.jl
Coverage.process_folder: Skipping DummyPackage.jl.30791.cov, not a .jl file
Reading data file coverage/lcov.info
Found 1 entries.
No common filename prefix found!
Writing .css and .png files.
Generating output.
Processing file src/DummyPackage.jl
genhtml: ERROR: cannot read src/DummyPackage.jl
ERROR: failed process: Process(`genhtml -t 'on branch master' -o coverage coverage/lcov.info`, ProcessExited(2)) [2]
Stacktrace:
 [1] pipeline_error(::Base.Process) at ./process.jl:682
 [2] run(::Cmd) at ./process.jl:651
 [3] (::LocalCoverage.##2#3{Bool})() at /home/simon/.julia/v0.6/LocalCoverage/src/LocalCoverage.jl:67
 [4] cd(::LocalCoverage.##2#3{Bool}, ::String) at ./file.jl:70
 [5] generate_coverage(::String) at /home/simon/.julia/v0.6/LocalCoverage/src/LocalCoverage.jl:58
```

After playing around with the code for a bit, it seems the problem is that the `lcov.info` file written [here](https://github.com/tpapp/LocalCoverage.jl/blob/555bd981b895e1208ff1a9935a541aab18b11876/src/LocalCoverage.jl#L63) contains relative path names, and (my version of) `genhtml` tries to resolve them within `/coverage` rather than the package root folder if you pass the `-o coverage` option (`genhtml` works fine if I call it without the `-o coverage` from the package root folder, but then you get all the html files among your source code and no one wants that). It seems you can avoid this problem if you call `process_folder()` with the absolute path to the source files, i.e. the following function works fine for me:

```
function coverage(pkg)
    Pkg.test(pkg, coverage=true)
    
    println()
    
    info("Processing coverage output")
    cov = Coverage.process_folder(Pkg.dir(pkg)*"/src");
    Coverage.LCOV.writefile(Pkg.dir(pkg)*"/coverage/lcov.info", cov)
    info("Coverage output processed")
    
    println()
    
    info("Removing coverage files")
    Coverage.clean_folder(Pkg.dir(pkg))
    info("Coverage files removed")
    
    println()
    
    info("Assembling coverage report")
    run(`genhtml -o $(Pkg.dir(pkg))/coverage $(Pkg.dir(pkg))/coverage/lcov.info`)
    info("Coverage report assembled at $(Pkg.dir(pkg))/coverage/index.html")

    return nothing
end
```

This might be an issue with my version of `genhtml` (1.10), but if it can be made to work even with this version why not do it?

**Comment by tpapp** [comment]
Thanks for investigating the issue. I am curious what distribution you are using, since genhtml `1.11` came out [4 years ago](https://github.com/linux-test-project/lcov/tree/v1.11).

**Comment by tpapp** [comment]
Eg in Ubuntu `1.10` was last provided by [14.04 LTS (Trusty)](https://packages.ubuntu.com/search?keywords=lcov).

**Comment by ettersi** [comment]
Ubuntu 14.04 is the version I am on, and I installed genhtml using apt.

**Comment by tpapp** [comment]
I would be happier if I could fix this with a command line parameter to `genhtml` alone. I will get Trusty running in Docker and explore this issue, but suggestions are welcome.

At the same time, I have to admit that my first suggestion would be upgrading to at least 16.04 LTS if possible. Are you planning that at some point?

**Comment by ettersi** [comment]
Not really. Why fix it if it ain't broke, and for all I know there isn't much broke on 14.04 yet.

**Comment by ettersi** [comment]
My reason for reporting here wasn't so much to push you into changing anything, though, but rather for having the issue documented somewhere and maybe get some feedback. For now, I am perfectly happy with my own little function which I can mess around with to my own liking. So if you want to close without taking any action, that would be absolutely fine with me.

**Comment by tpapp** [comment]
Thanks for the clarification, I think I will close, and suggest a recent `lcov` in the README.

**Comment by tpapp** [comment]
@ettersi, can you please give me the output of 
```sh
genhtml -v
```
on your setup? I could test the string and at least give a warning during package build.

**Comment by ettersi** [comment]
```
> genhtml -v
genhtml: LCOV version 1.10
```
