### ISSUE TITLE
genhtml version warning does not work

### ISSUE THREAD

**Issue by tpapp** [tpapp/LocalCoverage.jl#2]
(continuing [this discussion](https://github.com/tpapp/LocalCoverage.jl/commit/6cd1257d9f16752ed30a96dc34d15acd93a1e13c#commitcomment-28250866) here)

@ettersi, can you please run a `Pkg.build("LocalCoverage")` and tell me if it gives the warning?

**Comment by ettersi** [comment]
This works!

```
julia> Pkg.build("LocalCoverage")
INFO: Building MbedTLS
INFO: Building LocalCoverage
WARNING: The installed version of `genhtml` is 1.10.0, HTML generation may not work.
See https://github.com/tpapp/LocalCoverage.jl/issues/1 for workarounds.
```

**Comment by tpapp** [comment]
I am under the impression that this is working then, OK if I close the issue?

**Comment by ettersi** [comment]
Fine with me. Do I understand correctly that the package gets "built" (i.e. `deps/build.jl` gets run) automatically when you install it via `Pkg.add`, once the package is registered?

**Comment by tpapp** [comment]
(Sorry for the late reply). Yes.
