### ISSUE TITLE
New code coverage format always leads to 100% coverage

### ISSUE THREAD

**Issue by Paethon** [tpapp/LocalCoverage.jl#6]
It seems that the coverage file format that Julia produces (0.7) contains a `-` instead of `0` for lines which have not been covered at all.

Because of this, the html-File always reports 100% coverage

**Comment by tpapp** [comment]
Thanks for reporting, but I am not sure this is the right place, this package just uses those tools and the fix should from from upstream.

**Comment by Paethon** [comment]
Probably true. I (probably wrongly) assumed that the change of the format was intentional

**Comment by tpapp** [comment]
Furthermore, I can't replicate this: I tried on some packages and I get <100% coverage (which matches that calculated by coveralls.io). 

Please provide more specific information, eg version of Julia (ideally, please try 1.0), Coverage, and a public package I can test on.

**Comment by tpapp** [comment]
Not able to replicate, closing.
